IF
Global("StartEndBios","AR6200",1)
InParty("HGSLV01")
Global("BalthazarFights","GLOBAL",1)
Global("EhlasBio","AR6200",0)
THEN
RESPONSE #100
SetGlobal("EhlasBio","AR6200",1)
TextScreen("HG_balt")
SmallWait(1)
Continue()
END

IF
Global("StartEndBios","AR6200",1)
InParty("HGSLV01")
!Global("BalthazarFights","GLOBAL",1)
Global("EhlasBio","AR6200",0)
THEN
RESPONSE #100
SetGlobal("EhlasBio","AR6200",1)
TextScreen("HG_Noba")
SmallWait(1)
Continue()
END





